name: vy_language_tag
description: A representation of a language tag. It can be used in translation functions.
version: 0.1.3
homepage: https://github.com/giorgiofran/vy_language_tag

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  vy_string_utils: ^0.3.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
