name: vy_language_tag
description: A representation of a language tag as per IETF BCP 47 specs. It can be used in translation functions.
version: 0.2.1
homepage: https://github.com/giorgiofran/vy_language_tag

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vy_string_utils: ^0.4.0 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0 
