name: vy_language_tag
description: A representation of a language tag as per IETF BCP 47 specs. It can be used in translation functions.
version: 0.2.0-nullsafety
homepage: https://github.com/giorgiofran/vy_language_tag

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  vy_string_utils: 0.4.0-nullsafety #^0.3.2

dev_dependencies:
  pedantic: 1.10.0-nullsafety.3 #^1.8.0
  test: 1.16.0-nullsafety.13 #^1.6.0
