name: vy_language_tag
description: A representation of a language tag
version: 0.1.1
# homepage: https://www.example.com
# author: giorgio <giorgiofran@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  vy_string_utils:
    git:
      url: "https://github.com/giorgiofran/vy_string_utils"
    #path: ../../git/vy_string_utils

dev_dependencies:
  pedantic: 1.8.0
  test: ^1.6.0
